services:
  - type: web
    name: kuznechny-user
    runtime: docker
    repo: https://github.com/ananima77-ship-it/kuznechny-user.git
    plan: free
    region: frankfurt
    branch: main
    buildCommand: composer install --no-interaction --prefer-dist --optimize-autoloader
    startCommand: php artisan serve --host=0.0.0.0 --port=${PORT}
    envVars:
      - key: APP_KEY
        value: base64:Iv2yz/TI0Xw/u1AMnjqATVF5RBED2C+eQQDFwqRrqc4=
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        value: postgresql://kuznechny_db_user:Vgquua2iQGg818G0y1ozhL8iXHNK8ikf@dpg-d6p2h2ea2pns73f59410-a.frankfurt-postgres.render.com/kuznechny_db
